#!/bin/bash
if [${UID} -ne 0]
then
echo
echo "you need root access"
echo
exit 1
fi
## check number of processors
c= `nproc`
if [ ${c} -eq 1 ]
then 
	echo "this server is very small"
	sleep 10
	exit 2

fi	
